//! `forgemax init` — generate a starter configuration file.

use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::Args;

/// Arguments for the init subcommand.
#[derive(Debug, Args)]
pub struct InitArgs {
    /// Skip interactive prompts and use defaults.
    #[arg(long)]
    pub non_interactive: bool,

    /// Overwrite existing config file.
    #[arg(long)]
    pub force: bool,

    /// Output file path.
    #[arg(long, default_value = "forge.toml")]
    pub output: PathBuf,

    /// Use a named example template (e.g., "production").
    #[arg(long)]
    pub example: Option<String>,
}

/// Default config template with commented servers.
const DEFAULT_TEMPLATE: &str = r#"# Forge Configuration
# Generated by `forgemax init`
#
# Environment variables are expanded: ${VAR_NAME}
# Protect this file: chmod 600 forge.toml

# ─── Downstream Servers ─────────────────────────────────────────────
#
# Uncomment and configure the servers you need:
#
# [servers.narsil]
# command = "narsil-mcp"
# args = ["--repos", "."]
# transport = "stdio"
# timeout_secs = 30
#
# [servers.github]
# command = "docker"
# args = ["run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", "ghcr.io/github/github-mcp-server"]
# transport = "stdio"
# timeout_secs = 30

# ─── Sandbox Settings ───────────────────────────────────────────────

[sandbox]
timeout_secs = 5
max_heap_mb = 64
max_concurrent = 8
max_tool_calls = 50
execution_mode = "child_process"

# ─── Worker Pool (optional) ─────────────────────────────────────────
#
# [sandbox.pool]
# enabled = true
# min_workers = 2
# max_workers = 8
# max_idle_secs = 60
# max_uses = 50

# ─── Session Stash (optional) ───────────────────────────────────────
#
# [sandbox.stash]
# max_keys = 256
# max_value_size_mb = 16
# max_total_size_mb = 128
# default_ttl_secs = 3600
# max_ttl_secs = 86400
"#;

/// Execute the init command.
pub async fn execute(args: &InitArgs) -> Result<()> {
    // Refuse to overwrite without --force
    if args.output.exists() && !args.force {
        anyhow::bail!(
            "config file already exists: {}. Use --force to overwrite.",
            args.output.display()
        );
    }

    let content = match args.example.as_deref() {
        Some("production") => include_str!("../../forge.toml.example.production").to_string(),
        Some(other) => {
            anyhow::bail!(
                "unknown example template: '{}'. Available: production",
                other
            );
        }
        None => {
            if args.non_interactive {
                DEFAULT_TEMPLATE.to_string()
            } else {
                // Non-interactive for now (interactive prompts are a future enhancement)
                DEFAULT_TEMPLATE.to_string()
            }
        }
    };

    // Verify the generated config parses
    forge_config::ForgeConfig::from_toml(&content)
        .context("generated config failed to parse (this is a bug)")?;

    // Write the file
    std::fs::write(&args.output, &content)
        .with_context(|| format!("failed to write config to {}", args.output.display()))?;

    // Set file permissions on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&args.output, std::fs::Permissions::from_mode(0o600))
            .with_context(|| format!("failed to set permissions on {}", args.output.display()))?;
    }

    eprintln!("Created {}", args.output.display());
    #[cfg(unix)]
    eprintln!("  permissions: 0600 (owner read/write only)");
    eprintln!("  Edit the file to add your downstream servers.");

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn in_01_default_template_parses() {
        forge_config::ForgeConfig::from_toml(DEFAULT_TEMPLATE)
            .expect("default template must parse");
    }

    #[test]
    fn in_02_default_template_has_child_process() {
        let config = forge_config::ForgeConfig::from_toml(DEFAULT_TEMPLATE).unwrap();
        assert_eq!(
            config.sandbox.execution_mode.as_deref(),
            Some("child_process")
        );
    }

    #[test]
    fn in_03_default_template_no_active_env_vars() {
        // Check that no uncommented lines reference env vars
        let active_lines: String = DEFAULT_TEMPLATE
            .lines()
            .filter(|l| !l.trim_start().starts_with('#'))
            .collect::<Vec<_>>()
            .join("\n");
        let vars = crate::common::find_env_var_refs(&active_lines);
        assert!(
            vars.is_empty(),
            "default template should not have active env var refs, found: {:?}",
            vars
        );
    }

    #[test]
    fn in_04_production_template_parses() {
        let content = include_str!("../../forge.toml.example.production");
        forge_config::ForgeConfig::from_toml(content).expect("production template must parse");
    }

    #[tokio::test]
    async fn in_05_refuses_overwrite_without_force() {
        let dir = std::env::temp_dir().join("forge-init-test-overwrite");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("forge.toml");
        std::fs::write(&path, "existing content").unwrap();

        let args = InitArgs {
            non_interactive: true,
            force: false,
            output: path.clone(),
            example: None,
        };
        let result = execute(&args).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("already exists"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[tokio::test]
    async fn in_06_force_overwrite() {
        let dir = std::env::temp_dir().join("forge-init-test-force");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("forge.toml");
        std::fs::write(&path, "old content").unwrap();

        let args = InitArgs {
            non_interactive: true,
            force: true,
            output: path.clone(),
            example: None,
        };
        let result = execute(&args).await;
        assert!(result.is_ok());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("[sandbox]"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[tokio::test]
    async fn in_07_custom_output_path() {
        let dir = std::env::temp_dir().join("forge-init-test-custom");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("custom.toml");

        let args = InitArgs {
            non_interactive: true,
            force: false,
            output: path.clone(),
            example: None,
        };
        let result = execute(&args).await;
        assert!(result.is_ok());
        assert!(path.exists());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[tokio::test]
    async fn in_08_production_example_output() {
        let dir = std::env::temp_dir().join("forge-init-test-production");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("forge.toml");

        let args = InitArgs {
            non_interactive: true,
            force: false,
            output: path.clone(),
            example: Some("production".into()),
        };
        let result = execute(&args).await;
        assert!(result.is_ok());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("circuit_breaker = true"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn in_09_unix_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let dir = std::env::temp_dir().join("forge-init-test-perms");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("forge.toml");

        let args = InitArgs {
            non_interactive: true,
            force: false,
            output: path.clone(),
            example: None,
        };
        execute(&args).await.unwrap();

        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600, "expected 0600, got {:o}", mode);
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn in_10_default_template_mentions_server_examples() {
        // The default template should reference common servers to help users
        // discover what's available, even if commented out.
        assert!(
            DEFAULT_TEMPLATE.contains("narsil"),
            "template should mention narsil as example server"
        );
        assert!(
            DEFAULT_TEMPLATE.contains("github"),
            "template should mention github as example server"
        );
    }

    #[tokio::test]
    async fn in_11_production_example_has_circuit_breakers() {
        let content = include_str!("../../forge.toml.example.production");
        let config = forge_config::ForgeConfig::from_toml(content).unwrap();

        // Production config should have circuit breakers enabled on servers
        let has_cb = config
            .servers
            .values()
            .any(|s| s.circuit_breaker == Some(true));
        assert!(has_cb, "production example should enable circuit breakers");

        // Should have strict groups for isolation
        let has_strict = config.groups.values().any(|g| g.isolation == "strict");
        assert!(has_strict, "production example should have strict groups");
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn in_12_production_example_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let dir = std::env::temp_dir().join("forge-init-test-prod-perms");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("forge.toml");

        let args = InitArgs {
            non_interactive: true,
            force: true,
            output: path.clone(),
            example: Some("production".into()),
        };
        execute(&args).await.unwrap();

        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(
            mode, 0o600,
            "production config should be 0600, got {:o}",
            mode
        );

        // Verify the file content is the production template
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("circuit_breaker"));
        std::fs::remove_dir_all(&dir).ok();
    }
}
